name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: List dist files
        run: cd dist && ls

      - name: Configure AWS CLI
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/config
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/config
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/config
          echo "region = us-east-2" >> ~/.aws/config

      - name: Borrar lo que se encuentra en el bucket
        run: aws s3 rm s3://pipeline-yecid --recursive

      - name: Subir los archivos de dist para el bildeo que se sube en el bucket
        run: aws s3 cp ./dist/pipeline/browser s3://pipeline-yecid --recursive
